name: Run PHPCS

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to use'
        required: true
        type: string

permissions:
  contents: read

jobs:
  phpcs:
    name: PHPCS Coding Standards
    runs-on: [self-hosted]
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Configure Git for Safe Directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none
          tools: cs2pr

      - name: Restore PHPCS cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: tests/_output/phpcs-cache.json
          key: phpcs-cache-${{ runner.os }}-php${{ inputs.php-version }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            phpcs-cache-${{ runner.os }}-php${{ inputs.php-version }}-

      - name: Validate composer.json
        run: composer validate --no-check-publish

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0

      - name: Run PHPCS
        id: phpcs
        run: composer lint -- --report-full --report-checkstyle=./tests/_output/phpcs-report.xml

      - name: Save PHPCS cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: ${{ !cancelled() && steps.phpcs.outcome != 'skipped' }}
        with:
          path: tests/_output/phpcs-cache.json
          key: phpcs-cache-${{ runner.os }}-php${{ inputs.php-version }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Show PHPCS results in PR
        if: ${{ !cancelled() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./tests/_output/phpcs-report.xml
