name: Run Jest Tests

on:
  workflow_call:
    inputs:
      coverage:
        description: 'Enable code coverage'
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  jest:
    name: Jest Unit Tests${{ inputs.coverage && ' with coverage' || '' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run Jest tests${{ inputs.coverage && ' with coverage' || '' }}
        run: npm run test:js${{ inputs.coverage && ':coverage' || '' }}

      - name: Upload code coverage report to Codecov
        if: ${{ inputs.coverage }}
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/_output/js-coverage/lcov.info
          flags: jest
          fail_ci_if_error: false

      - name: Upload HTML coverage report as artifact
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: jest-code-coverage
          path: tests/_output/js-coverage/lcov-report
          retention-days: 7
          if-no-files-found: ignore
